In [12]:

import numpy as np, pandas as pd, matplotlib.pyplot as plt 
from sklearn import tree, metrics, model_selection, preprocessing

In [13]:
df = pd.read_csv('iris.csv')
df.head(5)

df['species_label'],i = pd.factorize(df['species'])
df['species'].unique()
df['species_label'].unique()

array([0, 1, 2], dtype=int64)

In [15]:
y = df['species_label'] #Dependent feature
x = df[['sepal.length', 'sepal.width']] #Independent features (subset)

In [16]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y,test_size=0.3, random_state=0)

In [17]:
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
dtree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [19]:
y_pred = dtree.predict(x_test)

accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.67
[[16  0  0]
 [ 1  5 12]
 [ 0  2  9]]
